### ISSUE TITLE
Spanish subdivisions are in double language with no space/split character

### ISSUE THREAD

**Issue by LunaticMuch** [wooorm/iso-3166#5] opened 2023-03-15 10:43 UTC
I am looking at the library and caught a possible issue. In Spain some subdivisions have the name in 2 languages. However, the string of the name concatenates the two versions.

Example:

```
{ code: 'ES-NA', name: 'NavarraNafarroa', parent: true },
```
This is `Navarra` in Spanish, and `Nafarroa` in Basque. But the name is not usable in this way. 

Either the object should contain the two languages, or allow a better split. In theory, the iso table contains the [language code](https://www.iso.org/obp/ui/#iso:code:3166:ES) which would make this much easier.

Shall we consider to refactor the list including the language code?

**Comment by LunaticMuch** [comment] 2023-03-15 11:02
It feels not consistent though, see for Italy
```
  {
    code: 'IT-32',
    name: 'Trentino-Alto Adige, Trentino-Südtirol',
    parent: true
  },
```

The double language is treated with a comma

**Comment by wooorm** [comment] 2023-03-15 11:36
Hi! That’s already solved.

* https://github.com/wooorm/iso-3166/blob/7a9ced434bc184dfee7451c28e9c5d16a4d0e445/2.js#L6275
* https://github.com/wooorm/iso-3166/commit/06504096e2d2266d0427a5ebc49ff2458161f7a3
* https://github.com/wooorm/iso-3166/releases/tag/4.2.0

Duplicate of #3

**Closed as not planned by wooorm** 2023-03-15 11:36 UTC
